name: "Nix Setup"
description: "Sets up Nix and Nix-taylored GitHub Caching"
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@v22
    - uses: DeterminateSystems/magic-nix-cache-action@v14
      with:
        use-flakehub: false
