name: "Checks"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
    inputs:
      working-directory:
        description: "Path to directory containing flake.nix"
        type: string
        default: "."

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    name: "Flake Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/nix-setup
      - name: "Flake Checker"
        uses: DeterminateSystems/flake-checker-action@v13
        with:
          flake-lock-path: "${{ inputs.working-directory }}/flake.lock"
          nixpkgs-keys: nixpkgs-stable,nixpkgs-unstable
          fail-mode: true
      - name: "Flake Check"
        run: "nix flake check --accept-flake-config ${{ inputs.working-directory }}"
