name: "Nix Remote Builder"
run-name: "${{ inputs.target != '' && format('Nix Remote: {0} [{1}]', inputs.target, inputs.session_id) || format('Nix Remote: [{0}]', inputs.session_id) }}"

on:
  workflow_dispatch:
    inputs:
      session_id:
        description: "Unique session identifier"
        required: true
        type: string
      target:
        description: "Target or Nix command being executed"
        required: false
        type: string
        default: ""
      matrix:
        description: "JSON matrix specification ({ include: [...] })"
        required: true
        type: string
      timeout_startup:
        description: "Wait for first connection in seconds"
        default: 300
        type: number
      timeout_idle:
        description: "Idle timeout between disconnections in seconds"
        default: 300
        type: number
      timeout_linger:
        description: "Grace period after completion signal in seconds"
        default: 0
        type: number

jobs:
  remote-builder:
    uses: Malix-Labs/Nix_Remote-Builders-Distributed/.github/workflows/nix-builder.yml@main
    with:
      session_id: ${{ inputs.session_id }}
      target: ${{ inputs.target }}
      matrix: ${{ inputs.matrix }}
      environment: "Nix Builders"
      timeout_startup: ${{ format('{0}', inputs.timeout_startup) }}
      timeout_idle: ${{ format('{0}', inputs.timeout_idle) }}
      timeout_linger: ${{ format('{0}', inputs.timeout_linger) }}
    secrets: inherit
