name: "Update"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      inputs:
        description: "A space-separated list of inputs to update. Leave empty to update all inputs."
        required: false
        type: string
      nix-options:
        description: "Options to pass to nix command"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    environment: "Malix - GitHub App" # ID:18767037302
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: "write"
          permission-pull-requests: "write"

      - uses: actions/checkout@v7
      - uses: ./.github/actions/nix-setup

      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          token: ${{ steps.app-token.outputs.token }}
          git-author-name: ${{ github.event_name == 'workflow_dispatch' && github.actor || format('{0}[bot]', steps.app-token.outputs.app-slug) }}
          git-author-email: ${{ github.event_name == 'workflow_dispatch' && format('{0}+{1}@users.noreply.github.com', github.actor_id, github.actor) || format('{0}+{1}[bot]@users.noreply.github.com', vars.APP_ID, steps.app-token.outputs.app-slug) }}
          git-committer-name: "${{ steps.app-token.outputs.app-slug }}[bot]"
          git-committer-email: ${{ format('{0}+{1}[bot]@users.noreply.github.com', vars.APP_ID, steps.app-token.outputs.app-slug) }}
          inputs: ${{ github.event.inputs.inputs }}
          nix-options: ${{ github.event.inputs.nix-options }}
          branch: "ci/update"
          path-to-flake-dir: "nix"
          pr-labels: "Update"
          commit-msg: &msg "update: ${{ github.event.inputs.inputs || 'all' }}"
          pr-title: *msg
