name: "Update"

on:
  workflow_dispatch:
    inputs:
      inputs:
        description: "A space-separated list of inputs to update. Leave empty to update all inputs."
        required: false
        type: string
      nix-options:
        description: "Options to pass to nix command"
        required: false
        type: string
  workflow_call:
    inputs:
      working-directory:
        description: "Path to directory containing flake.nix"
        type: string
        default: "."

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    environment: "Malix - GitHub App" # ID: 18767037302
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: "write"
          permission-pull-requests: "write"

      - name: Get Dispatch User Info
        id: dispatch-user
        run: gh api "/users/${{ github.actor }}" --jq '"author=" + (.name // .login) + " <" + (.email // (.id|tostring + "+" + .login + "@users.noreply.github.com")) + ">"' >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@v7
      - uses: ./.github/actions/nix-setup

      - uses: DeterminateSystems/update-flake-lock@v28
        env:
          TITLE: "update: ${{ inputs.inputs || 'all' }}"
        with:
          token: ${{ steps.app-token.outputs.token }}
          git-author-name: &bot_name "${{ steps.app-token.outputs.app-slug }}[bot]"
          git-author-email: &bot_email ${{ format('{0}+{1}[bot]@users.noreply.github.com', vars.USER_ID, steps.app-token.outputs.app-slug) }}
          git-committer-name: *bot_name
          git-committer-email: *bot_email
          inputs: ${{ inputs.inputs }}
          nix-options: ${{ inputs.nix-options }}
          branch: "ci/update/${{ inputs.inputs || 'all' }}"
          path-to-flake-dir: ${{ inputs.working-directory }}
          pr-labels: "Update"
          pr-title: ${{ env.TITLE }}

          # Bugged: https://github.com/DeterminateSystems/update-flake-lock/issues/294
          commit-msg: |
            ${{ env.TITLE }}

            Co-authored-by: ${{ steps.dispatch-user.outputs.author }}
